// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NerdStore.WebApp.MVC.Data;

namespace NerdStore.WebApp.MVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619220500_InitialIdentity")]
    partial class InitialIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            ApplicationDbContextModelSnapshot.BuildIdentityModel(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
